### ISSUE TITLE
IsoCompat trait not public

### ISSUE THREAD

**Issue by fhaefemeier** [nickzana/rust-iso639#3]
I really like this crate and use it in my project. After upgrade to latest version 0.5.1 I recognized a few major changes. One of is IsoCompat trait is no longer public. Are. any plans to change it or maybe a bug?

Do you plan to make this crate official public and standalone? I understand your readme, it is implemented as a dependency for another project.

**Comment by nickzana** [comment]
Sorry for the breaking API change, that was unintentional. I updated the tests in lib.rs to make sure that won't happen again. I didn't realize anyone else used the crate, I will be more careful about any potential changes in the future. Feel free to share your particular use case if you'd like test cases/features added.

Fixed in 194e63d. Version was bumped to 0.6.0.
